import type { ExecutionReport } from './contract.js';
import { escapeHtml, formatDate, formatDuration, metaRow } from './html-report-format.js';
import { outcomeStamp } from './html-report-flow-view.js';
import { renderCase, renderRunDetail } from './html-report-persona-view.js';
import { renderCoverageView } from './html-report-coverage-view.js';
import { REPORT_CSS } from './html-report-css.js';

/**
 * Renders report.html — an investigation board (persona case files -> flow evidence -> findings)
 * over the same `ExecutionReport` data that drives report.json.
 */

export function renderHtmlReport(report: ExecutionReport): string {
  const stamp = outcomeStamp(report);
  const cases = report.runs.map((run, index) => renderCase(run, index, index === 0)).join('');
  const details = report.runs.map((run, index) => renderRunDetail(run, index, index === 0)).join('');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(report.url)} — execution report</title>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,450;0,9..144,560;0,9..144,650;1,9..144,500&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap">
<style>
${REPORT_CSS}
</style>
</head>
<body>
<div class="page">
  <div class="run-head">
    <div>
      <div class="eyebrow">Execution</div>
      <h1>${escapeHtml(report.url)}</h1>
      ${metaRow([
        `<span class="chip muted">${escapeHtml(report.command)}</span>`,
        `<span class="mono">${formatDate(report.startedAt)}</span>`,
        `duration <span class="mono">${escapeHtml(formatDuration(report.startedAt, report.completedAt))}</span>`,
      ])}
      <div class="execution-id">execution <span class="mono">${escapeHtml(report.executionId)}</span></div>
    </div>
    <div class="stamp ${stamp.tone}"><span class="dot"></span>${escapeHtml(stamp.label)}</div>
  </div>

  <div class="stats">
    <div class="stat"><div class="n mono">${report.summary.runs}</div><div class="l">personas run</div></div>
    <div class="stat"><div class="n mono">${report.summary.flowsFound}</div><div class="l">flows discovered</div></div>
    <div class="stat"><div class="n mono">${report.summary.replayConfirmed}</div><div class="l">replay-confirmed</div></div>
    <div class="stat"><div class="n mono">${report.summary.generatedTests}</div><div class="l">tests generated</div></div>
    <div class="stat"><div class="n mono">${report.summary.confirmedFindings}</div><div class="l">findings confirmed</div></div>
    <div class="stat"><div class="n mono">${report.summary.needsReview}</div><div class="l">needs review</div></div>
  </div>

  <nav class="top-tabs" role="tablist" aria-label="Report views">
    <button class="top-tab" data-view="view-coverage" aria-current="true">Coverage</button>
    <button class="top-tab" data-view="view-personas" aria-current="false">Personas</button>
  </nav>

  ${renderCoverageView(report)}

  <section id="view-personas" hidden>
    <div class="board">
      <nav class="case-list" role="tablist" aria-label="Personas">${cases}</nav>
      <div class="detail">${details}</div>
    </div>
  </section>

  <footer class="page-foot">
    <span>report.html</span>
    <span>generated by appwalk</span>
  </footer>
</div>

<script>
  document.querySelectorAll('.top-tab').forEach(function(tab){
    tab.addEventListener('click', function(){
      document.querySelectorAll('.top-tab').forEach(function(t){ t.setAttribute('aria-current','false'); });
      tab.setAttribute('aria-current','true');
      document.getElementById('view-coverage').hidden = tab.dataset.view !== 'view-coverage';
      document.getElementById('view-personas').hidden = tab.dataset.view !== 'view-personas';
    });
  });
  document.querySelectorAll('.case').forEach(function(btn){
    btn.addEventListener('click', function(){
      document.querySelectorAll('.case').forEach(function(b){ b.setAttribute('aria-current','false'); });
      btn.setAttribute('aria-current','true');
      document.querySelectorAll('.persona-detail').forEach(function(p){ p.hidden = true; });
      document.getElementById(btn.dataset.case).hidden = false;
    });
  });
</script>
</body>
</html>`;
}
